/**
 * @file MtcImFthttpConstants.java
 * @brief MtcImFthttpConstants constants
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.cmcc.app.lemon;

/**
 * @brief MtcImFthttpConstants constants
 */
public interface MtcImFthttpConstants {
  public final static String MTC_IM_FTHTTP_CONT_TXT_PLAIN = "text/plain"; /**< @brief text/plain content */
  public final static String MTC_IM_FTHTTP_CONT_TXT_HTML = "text/html"; /**< @brief text/html content */
  public final static String MTC_IM_FTHTTP_CONT_IMG_JPEG = "image/jpeg"; /**< @brief image/jpeg content */
  public final static String MTC_IM_FTHTTP_CONT_IMG_GIF = "image/gif"; /**< @brief image/gif content */
  public final static String MTC_IM_FTHTTP_CONT_IMG_BMP = "image/bmp"; /**< @brief image/bmp content */
  public final static String MTC_IM_FTHTTP_CONT_IMG_PNG = "image/png"; /**< @brief image/png content */
  // EN_MTC_IM_FTHTTP_IMDN_ITYPE 
  public final static int EN_MTC_IM_FTHTTP_IMDN_UNKNOWN = 0; /**< @brief unknown message */
  public final static int EN_MTC_IM_FTHTTP_IMDN_REG = EN_MTC_IM_FTHTTP_IMDN_UNKNOWN + 1; /**< @brief regular message */
  public final static int EN_MTC_IM_FTHTTP_IMDN_DELI = EN_MTC_IM_FTHTTP_IMDN_REG + 1; /**< @brief message with delivery notification request */
  public final static int EN_MTC_IM_FTHTTP_IMDN_DISP = EN_MTC_IM_FTHTTP_IMDN_DELI + 1; /**< @brief message with display notification request */
  public final static int EN_MTC_IM_FTHTTP_IMDN_BOTH = EN_MTC_IM_FTHTTP_IMDN_DISP + 1; /**< @brief message with delivery & display notification request */

}
